### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by caspervdw** [nens/threedi-openapi-client#34]
I see that since version 3.0.16, aiohttp has be come pinned. This is an issue because threedi-api-client is distributed as a library. It is easy to get dependency clashes if you pin versions so exactly. Therefore you should not pin dependencies in libraries.

Why was this necessary? Is it possible to make a weaker pin? Or put the pin in the application that uses threedi-api-client?

Or maybe even better: make the whole asyncio part optional? In Lizard, we are now pulling in 5 obsolete dependencies..

**Comment by larsclaussen** [comment]
@caspervdw I just saw your issue now somehow, so sorry for the late reply. 

For now I put a weaker pin but it but indeed be nice to make the whole async part optional. But it does not have my prio at the moment.

**Comment by caspervdw** [comment]
This already saves a lot of trouble, thanks. I understand that making the whole aiohttp stuff is not feasible at the moment.
